export const genres = [
  "Todos",
  "Acción",
  "Artes Marciales",
  "Aventuras",
  "Carreras",
  "Ciencia Ficción",
  "Comedia",
  "Demencia",
  "Demonios",
  "Deportes",
  "Drama",
  "Ecchi",
  "Escolares",
  "Espacial",
  "Fantasia",
  "Harem",
  "Histórico",
  "Infantil",
  "Juegos",
  "Magia",
  "Militar",
  "Misterio",
  "Musica",
  "Parodia",
  "Policía",
  "Psicológico",
  "Recuerdos de la vida",
  "Romance",
  "Samurai",
  "Seisen",
  "Shoujo",
  "Sobrenatural",
  "Superpoderes",
  "Suspenso",
  "Terror",
  "Vampiros",
  "Yuri",
];